##### Consider the below code to answer further questions:

In [1]:
import numpy as np

In [2]:
list = ['1','2','3','4','5']

In [3]:
array_list = np.array(object = list)

In [4]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

##### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [5]:
type(list)

list

In [7]:
array_list.dtype

dtype('<U1')

##### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [9]:
for element in list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [11]:
for element in array_list:
    print(element.dtype)

<U1
<U1
<U1
<U1
<U1


##### Q3. Considering the following changes in the variable, array_list:


Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [12]:
array_list = np.array(object = list, dtype = int)

In [13]:
array_list

array([1, 2, 3, 4, 5])

In [14]:
for element in list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [15]:
for element in array_list:
    print(element.dtype)

int32
int32
int32
int32
int32


yes there is difference betweeb list and array_list because the variable list contcains all the str datatypes whereas array-list contains all int datatypes.

##### Consider the below code to answer further questions:

In [16]:
import numpy as np

In [17]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

In [18]:
num_array = np.array(object=num_list)

In [19]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

##### Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [21]:
num_array.size

6

In [22]:
num_array.shape

(2, 3)

##### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [23]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

##### Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [26]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])